// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqpafqmdesegrgkvkuig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcGFmcW1kZXNlZ3Jna3ZrdWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTI2NjAsImV4cCI6MjA3MjM2ODY2MH0.Q3SwkTm7KUQirv8jSz9GRsGUIS3l5U0cej5_-I7ugaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});